import { Response } from 'express';
import { z } from 'zod';
import { pool, withTransaction } from '../config/db';
import { AuthRequest } from '../middleware/auth';

const createSchema=z.object({customer_id:z.string().uuid(),items:z.array(z.object({product_id:z.string().uuid(),quantity:z.number().int().positive()})).min(1)});
const nextNumber=async(client:any)=>{ const r=await client.query("SELECT COALESCE(MAX(CAST(SUBSTRING(challan_number FROM 9) AS INTEGER)),0)+1 AS n FROM challans WHERE challan_number LIKE 'CH-2026-%'"); return `CH-2026-${String(r.rows[0].n).padStart(5,'0')}`; };
export async function listChallans(req: AuthRequest,res: Response){ const r=await pool.query(`SELECT c.*, cu.name AS customer_name, u.name AS created_by_name FROM challans c JOIN customers cu ON cu.id=c.customer_id JOIN users u ON u.id=c.created_by ORDER BY c.created_at DESC`); res.json(r.rows); }
export async function getChallan(req: AuthRequest,res: Response){ const c=await pool.query(`SELECT c.*, cu.name AS customer_name FROM challans c JOIN customers cu ON cu.id=c.customer_id WHERE c.id=$1`,[req.params.id]); if(!c.rows[0]) return res.status(404).json({message:'Challan not found'}); const i=await pool.query('SELECT * FROM challan_items WHERE challan_id=$1',[req.params.id]); res.json({...c.rows[0],items:i.rows}); }
export async function createChallan(req: AuthRequest,res: Response){ const d=createSchema.parse(req.body); const result=await withTransaction(async client=>{ const customer=await client.query('SELECT id FROM customers WHERE id=$1',[d.customer_id]); if(!customer.rows[0]) { const e=new Error('Customer not found'); (e as any).status=404; throw e; } const number=await nextNumber(client); let total=0; const c=await client.query(`INSERT INTO challans(challan_number,customer_id,created_by) VALUES($1,$2,$3) RETURNING *`,[number,d.customer_id,req.user!.id]); for(const item of d.items){ const p=await client.query('SELECT id,name,sku,unit_price,current_stock FROM products WHERE id=$1',[item.product_id]); if(!p.rows[0]) { const e=new Error(`Product ${item.product_id} not found`); (e as any).status=404; throw e; } total+=item.quantity; await client.query(`INSERT INTO challan_items(challan_id,product_id,product_name_snapshot,sku_snapshot,unit_price_snapshot,quantity) VALUES($1,$2,$3,$4,$5,$6)`,[c.rows[0].id,p.rows[0].id,p.rows[0].name,p.rows[0].sku,p.rows[0].unit_price,item.quantity]); } await client.query('UPDATE challans SET total_quantity=$1 WHERE id=$2',[total,c.rows[0].id]); return {...c.rows[0],total_quantity:total}; }); res.status(201).json(result); }
export async function confirmChallan(req: AuthRequest,res: Response){ try { const result=await withTransaction(async client=>{ const c=await client.query('SELECT * FROM challans WHERE id=$1 FOR UPDATE',[req.params.id]); if(!c.rows[0]) { const e=new Error('Challan not found'); (e as any).status=404; throw e; } if(c.rows[0].status!=='DRAFT') { const e=new Error(`Only Draft challans can be confirmed. Current status: ${c.rows[0].status}`); (e as any).status=409; throw e; } const items=await client.query('SELECT * FROM challan_items WHERE challan_id=$1',[req.params.id]); for(const item of items.rows){ const p=await client.query('SELECT * FROM products WHERE id=$1 FOR UPDATE',[item.product_id]); if(Number(p.rows[0].current_stock)<Number(item.quantity)) { const e=new Error(`Insufficient stock for ${p.rows[0].name}. Available: ${p.rows[0].current_stock}, requested: ${item.quantity}`); (e as any).status=409; throw e; } } for(const item of items.rows){ await client.query('UPDATE products SET current_stock=current_stock-$1, updated_at=NOW() WHERE id=$2',[item.quantity,item.product_id]); await client.query(`INSERT INTO stock_movements(product_id,quantity,movement_type,reason,created_by) VALUES($1,$2,'OUT',$3,$4)`,[item.product_id,item.quantity,`Sales challan ${c.rows[0].challan_number}`,req.user!.id]); } const u=await client.query(`UPDATE challans SET status='CONFIRMED', updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id]); return u.rows[0]; }); res.json(result); } catch(error:any){ res.status(error.status??500).json({message:error.message??'Failed to confirm challan'}); } }
export async function cancelChallan(req: AuthRequest,res: Response){ const r=await pool.query(`UPDATE challans SET status='CANCELLED',updated_at=NOW() WHERE id=$1 AND status='DRAFT' RETURNING *`,[req.params.id]); if(!r.rows[0]) return res.status(409).json({message:'Only Draft challans can be cancelled'}); res.json(r.rows[0]); }
