import { Response } from 'express';
import { z } from 'zod';
import { pool, withTransaction } from '../config/db';
import { AuthRequest } from '../middleware/auth';

const schema = z.object({name:z.string().min(1),sku:z.string().min(1),category:z.string().min(1),unit_price:z.number().nonnegative(),current_stock:z.number().int().nonnegative().default(0),minimum_stock:z.number().int().nonnegative().default(0),warehouse_location:z.string().min(1)});
export async function listProducts(req: AuthRequest,res: Response){ const q=String(req.query.search??''); const r=await pool.query(`SELECT *, (current_stock <= minimum_stock) AS low_stock FROM products WHERE name ILIKE $1 OR sku ILIKE $1 OR category ILIKE $1 ORDER BY created_at DESC`,[`%${q}%`]); res.json(r.rows); }
export async function createProduct(req: AuthRequest,res: Response){ const d=schema.parse(req.body); const r=await withTransaction(async c=>{ const p=await c.query(`INSERT INTO products(name,sku,category,unit_price,current_stock,minimum_stock,warehouse_location) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[d.name,d.sku,d.category,d.unit_price,d.current_stock,d.minimum_stock,d.warehouse_location]); if(d.current_stock>0) await c.query(`INSERT INTO stock_movements(product_id,quantity,movement_type,reason,created_by) VALUES($1,$2,'IN','Initial stock',$3)`,[p.rows[0].id,d.current_stock,req.user!.id]); return p.rows[0]; }); res.status(201).json(r); }
export async function updateProduct(req: AuthRequest,res: Response){ const d=schema.partial().parse(req.body); const old=await pool.query('SELECT * FROM products WHERE id=$1',[req.params.id]); if(!old.rows[0]) return res.status(404).json({message:'Product not found'}); const keys=Object.keys(d); if(!keys.length) return res.status(400).json({message:'Nothing to update'}); const sets=keys.map((k,i)=>`${k}=$${i+1}`).join(','); const vals=keys.map(k=>(d as Record<string,unknown>)[k]); vals.push(req.params.id); const r=await pool.query(`UPDATE products SET ${sets}, updated_at=NOW() WHERE id=$${vals.length} RETURNING *`,vals); const before=Number(old.rows[0].current_stock), after=Number(r.rows[0].current_stock); const diff=after-before; if(diff!==0) await pool.query(`INSERT INTO stock_movements(product_id,quantity,movement_type,reason,created_by) VALUES($1,$2,$3,$4,$5)`,[req.params.id,Math.abs(diff),diff>0?'IN':'OUT','Manual stock adjustment',req.user!.id]); res.json(r.rows[0]); }
export async function stockMovements(req: AuthRequest,res: Response){ const r=await pool.query(`SELECT sm.*, p.name AS product_name, p.sku, u.name AS created_by_name FROM stock_movements sm JOIN products p ON p.id=sm.product_id JOIN users u ON u.id=sm.created_by WHERE sm.product_id=$1 ORDER BY sm.created_at DESC`,[req.params.id]); res.json(r.rows); }
